apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: epto-deployment
spec:
  replicas: 20
  template:
    metadata:
      labels:
        app: epto
    spec:
      containers:
      - name: cyclon
        image: cyclon:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APP
          value: "epto"
        - name: DEPLOYMENT_NAME
          value: "epto-deployment"
        - name: NUMBER_OF_THREADS
          value: '2'
        - name: NUMBER_OF_WORKERS
          value: '1'
#        - name: KUBECONTEXT
#          value: 'epto.cluster.k8s.local'
#        - name: KUBECONFIG
#          value: 'config'
        - name: VIEW_LIMIT
          value: "10"
        - name: SHUFFLE_LENGTH
          value: "8"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: LOG_FORMATTER
          value: "STANDARD"
        resources:
          limits:
            memory: 90Mi
            cpu: 60m
          requests:
            memory: 75Mi
            cpu: 40m
      - name: epto
        image: epto:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NUMBER_OF_THREADS
          value: '2'
        - name: NUMBER_OF_WORKERS
          value: '1'
        - name: BROADCAST_PROB
          value: '0.5'
        - name: FANOUT
          value: '2'
        - name: TTL
          value: '3'
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: LOG_FORMATTER
          value: "STANDARD"