apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kubeclient
        image: kubeclient:latest
        imagePullPolicy: Never
        env:
        - name: APP
          value: 'epto'
        - name: DEPLOYMENT_NAME
          value: 'epto-deployment'